%YAML:1.0

# PCD点云地图预处理
pcd_path: "/home/cetc21/xmf/my_slam_ws/slam_test/data/remove_ground/scans110.pcd"    #  PCD点云地图绝对路径
# 体素滤波是否
vexel_flag: 1    #  是否使用体素滤波降采样
voxel_filter_size: 0.1    #  栅格体素滤波边长
#统计滤波
statistic_flag: 1    #  是否使用统计滤波(默认为1)
statictis_filter_kmeans: 20    #  统计滤波最近邻点数
kmeans_factor: 4    #  统计滤波KMeans因子，用于控制KMeans的大小   //这个参数暂时没用到
statictis_filter_thred: 1    #  P统计滤波的方差阈值         //如果参数设置过小会导致边界点部分被剔除
thred_factor: 3    #  统计滤波方差阈值因子，用于控制方差阈值的大小   //这个参数暂时没用到
#条件滤波
pass_filter_maxHight: 50    #  条件滤波的最大高度值，也是点云地图转成栅格地图的最大点云高度值b      yuanshuju 2.5
pass_filter_minHight: -50    #  条件滤波的最小高度值，也是点云地图转成栅格地图的最小点云高度值  yaunshuju-0.60
#RANSAC
ransac_iters: 3000    #  去除地面点使用的RANSAC方法的迭代次数
ransac_distance_thre: 0.1    #  RANSAC拟合地面的距离阈值
#显示去除地面的点云
pcl_viewer: 1    #  是否显示去除地面后的点云
cloud_size_viewer: 1    #  点云显示时激光点的大小

